import { FurnitureModel } from '@shared/schema';

// Default furniture catalog with 35 models (5 per category)
export const DEFAULT_FURNITURE_CATALOG: FurnitureModel[] = [
  // Beds (5 models)
  {
    id: 1,
    name: 'Platform Bed',
    category: 'beds',
    modelUrl: '/models/beds/platform-bed.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 2,
    name: 'Upholstered Bed',
    category: 'beds',
    modelUrl: '/models/beds/upholstered-bed.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 3,
    name: 'Storage Bed',
    category: 'beds',
    modelUrl: '/models/beds/storage-bed.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 4,
    name: 'Canopy Bed',
    category: 'beds',
    modelUrl: '/models/beds/canopy-bed.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 5,
    name: 'Minimalist Bed',
    category: 'beds',
    modelUrl: '/models/beds/minimalist-bed.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },

  // Sofas (5 models)
  {
    id: 6,
    name: 'L-Sectional',
    category: 'sofas',
    modelUrl: '/models/sofas/l-sectional.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 7,
    name: 'Modern Sofa',
    category: 'sofas',
    modelUrl: '/models/sofas/modern-sofa.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 8,
    name: 'Chesterfield',
    category: 'sofas',
    modelUrl: '/models/sofas/chesterfield.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 9,
    name: 'Loveseat',
    category: 'sofas',
    modelUrl: '/models/sofas/loveseat.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 10,
    name: 'Modular Sofa',
    category: 'sofas',
    modelUrl: '/models/sofas/modular-sofa.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },

  // Chairs (5 models)
  {
    id: 11,
    name: 'Accent Chair',
    category: 'chairs',
    modelUrl: '/models/chairs/accent-chair.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1549497538-303791108f95?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 12,
    name: 'Office Chair',
    category: 'chairs',
    modelUrl: '/models/chairs/office-chair.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 13,
    name: 'Dining Chair',
    category: 'chairs',
    modelUrl: '/models/chairs/dining-chair.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 14,
    name: 'Recliner',
    category: 'chairs',
    modelUrl: '/models/chairs/recliner.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 15,
    name: 'Armchair',
    category: 'chairs',
    modelUrl: '/models/chairs/armchair.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },

  // Tables (5 models)
  {
    id: 16,
    name: 'Coffee Table',
    category: 'tables',
    modelUrl: '/models/tables/coffee-table.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1549497538-303791108f95?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 17,
    name: 'Dining Table',
    category: 'tables',
    modelUrl: '/models/tables/dining-table.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1549497538-303791108f95?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 18,
    name: 'Side Table',
    category: 'tables',
    modelUrl: '/models/tables/side-table.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 19,
    name: 'Console Table',
    category: 'tables',
    modelUrl: '/models/tables/console-table.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 20,
    name: 'Desk',
    category: 'tables',
    modelUrl: '/models/tables/desk.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },

  // Wall Decor (5 models)
  {
    id: 21,
    name: 'Wall Art',
    category: 'wall_decor',
    modelUrl: '/models/wall-decor/wall-art.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1549497538-303791108f95?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 22,
    name: 'Mirror',
    category: 'wall_decor',
    modelUrl: '/models/wall-decor/mirror.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 23,
    name: 'Shelf',
    category: 'wall_decor',
    modelUrl: '/models/wall-decor/shelf.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 24,
    name: 'Wall Clock',
    category: 'wall_decor',
    modelUrl: '/models/wall-decor/wall-clock.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 25,
    name: 'Wall Sconce',
    category: 'wall_decor',
    modelUrl: '/models/wall-decor/wall-sconce.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },

  // Dining (5 models)
  {
    id: 26,
    name: 'Dining Set',
    category: 'dining',
    modelUrl: '/models/dining/dining-set.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1549497538-303791108f95?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 27,
    name: 'Bar Cart',
    category: 'dining',
    modelUrl: '/models/dining/bar-cart.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 28,
    name: 'Buffet',
    category: 'dining',
    modelUrl: '/models/dining/buffet.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 29,
    name: 'China Cabinet',
    category: 'dining',
    modelUrl: '/models/dining/china-cabinet.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 30,
    name: 'Wine Rack',
    category: 'dining',
    modelUrl: '/models/dining/wine-rack.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },

  // Cutlery (5 models)
  {
    id: 31,
    name: 'Utensil Holder',
    category: 'cutlery',
    modelUrl: '/models/cutlery/utensil-holder.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1549497538-303791108f95?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 32,
    name: 'Cutting Board',
    category: 'cutlery',
    modelUrl: '/models/cutlery/cutting-board.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 33,
    name: 'Knife Block',
    category: 'cutlery',
    modelUrl: '/models/cutlery/knife-block.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 34,
    name: 'Spice Rack',
    category: 'cutlery',
    modelUrl: '/models/cutlery/spice-rack.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
  {
    id: 35,
    name: 'Kitchen Scale',
    category: 'cutlery',
    modelUrl: '/models/cutlery/kitchen-scale.gltf',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
    isDefault: true,
    uploadedBy: null,
    createdAt: new Date(),
  },
];

// Furniture categories
export const FURNITURE_CATEGORIES = [
  { id: 'beds', name: 'Beds', icon: '🛏️' },
  { id: 'sofas', name: 'Sofas', icon: '🛋️' },
  { id: 'chairs', name: 'Chairs', icon: '🪑' },
  { id: 'tables', name: 'Tables', icon: '🪑' },
  { id: 'wall_decor', name: 'Wall Decor', icon: '🖼️' },
  { id: 'dining', name: 'Dining', icon: '🍽️' },
  { id: 'cutlery', name: 'Cutlery', icon: '🍴' },
];

// Get furniture models by category
export const getFurnitureByCategory = (category: string): FurnitureModel[] => {
  return DEFAULT_FURNITURE_CATALOG.filter(item => item.category === category);
};

// Get furniture model by ID
export const getFurnitureById = (id: number): FurnitureModel | undefined => {
  return DEFAULT_FURNITURE_CATALOG.find(item => item.id === id);
};
